In [4]:
import numpy as np

### Basic Array Creation

# Creatation of List
How to create Lists in python?

In [1]:
# Answer Here
n=[1,2,3,4,5]

# Type
Accuire type of list in python.

In [3]:
# Answer Here
type(n)

list

# Creatation of Arrays
1.SIMPLE ARRAY CREATION

2.CHECKING THE TYPE

3.NUMERIC "TYPE" OF ELEMENTS OF ARRAYS

4.Array dim

5.Array Shape

6.BYTES PER ELEMENT

7.BYTES OF MEMORY USED, How many bytes for one array element

8.Total bytes in an Array

In [81]:
# Int array
# Answer Here
a=np.array([1,2,3],dtype=np.int32)
a

array([1, 2, 3])

In [80]:
# Decimal array
#Answer Here
b=np.array([1.2,4.53,23.6,24.43],dtype=np.float32)
b

array([ 1.2 ,  4.53, 23.6 , 24.43], dtype=float32)

9.Try to assign a float into an int32

10.Use .fill function # fill has the same behavior


In [77]:

g= np.array([1, 2, 3], dtype=np.int32)

g.fill(4.5)

g



array([4, 4, 4])

11.Add two  arrays

12.Multiple both arrays

13.Use ** operator in array operation

14.Create array from 0.0 to 11.0

15.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

16.Use np.arrange function tocreate an array with step of from 1.0 to 3.0

In [82]:
# Answer Here
c=np.arange(0.0,11.1,0.5)
c

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. ])

# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Extract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [136]:
# Answer Here 
a = np.array([0, 1, 2, 3, 4,5])
a

array([0, 1, 2, 3, 4, 5])

In [137]:
#Extract array indices from 1 to 3:
b=a[1:4]
b

array([1, 2, 3])

In [138]:
#Use negative indices as well
c=a[-4:-1]
c

array([2, 3, 4])

In [140]:
#Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
d=a[:3]
d

array([0, 1, 2])

In [147]:
#Grab last two elements
e=a[-2:]
e

array([4, 5])

In [153]:
#Grab every other element
f=a[0::2]
f

array([0, 2, 4])

In [164]:
#slicing the last two elements returns the data there
g=a[-2:]
g

array([4, 5])

In [170]:
#Can we insert an iterable of length two? or a scalar value 8.
#yes we can
h=a[-2:]
h[0]=8
h

array([8, 5])

In [200]:
#Changing values in a slice also changes the original array.
a = np.array([0, 1, 2, 3, 4, 5])
#slicing
b = a[1:6]
b[4]=99
print(a)
print(b)

[ 0  1  2  3  4 99]
[ 1  2  3  4 99]


In [211]:
#if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
a =np.array ([[0, 1, 2, 3, 4, 5],[1, 2, 3, 4, 5, 6],[2, 4, 6, 8, 10, 12]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12]])

In [224]:
#extract values from row 3 to onward and from col 0, 2 and 5
b=a[2:,[0,2,5]]
b

array([[ 2,  6, 12]])

In [262]:
#Perform some masking on a = np.arange(0,36).reshape(6,6) with mask = np.array([1, 0, 1, 0, 0, 1])
a=np.arange(0,36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [275]:
b=np.array([1,0,1,0,0,1])
mask=a[:,b==1]
mask

array([[ 0,  2,  5],
       [ 6,  8, 11],
       [12, 14, 17],
       [18, 20, 23],
       [24, 26, 29],
       [30, 32, 35]])

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

6.
Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum


In [283]:
#create an array with arange.
a=np.arange(0,20,2,dtype=(np.int64))
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int64)

In [285]:
# Answer Here
b= np.ones((3, 4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [287]:
c= np.zeros((2, 3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [288]:
d== np.eye(3)

array([[False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [291]:
e=np.empty((2, 2))
e

array([[ 1.2 ,  4.53],
       [23.6 , 24.43]])

In [292]:
f=np.full((3, 3), 7)
f

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [298]:
g=np.zeros((2, 3))
g.fill(5)
g

array([[5., 5., 5.],
       [5., 5., 5.]])

In [300]:
# Create the array a = np.arange(-15, 15).reshape(5, 6) ** 2
a = np.arange(-15, 15).reshape(5, 6) ** 2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [305]:
b=np.max(a, axis=1)
b

array([225,  81,   9,  64, 196])

In [309]:
#Mean of each column
c = np.mean(a, axis=0)
c

array([81., 76., 73., 72., 73., 76.])

In [312]:
#Position of the overall minimum (done from chatgpt)
d = np.unravel_index(np.argmin(a), a.shape)
d

(2, 3)

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [315]:
import numpy as np

# Two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Use zip to combine elements
c = zip(a, b)

# Create a new array with the sum of corresponding elements using a for loop
d = np.array([a + b for a, b in c])

print(a)
print(b)
print(d)


[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]


In [317]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

# Answer Here
c=zip(a,b)
d=np.array([a+b for a, b in c])
d

array([3, 5, 7, 9])

In [318]:
#For loop to add corresponding elements in two lists
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

# Answer Here
c=zip(a,b)
d=np.array([a+b for a, b in c])
d
# Answer Here

array([3, 5, 7, 9])

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING


In [321]:
# Answer Here
a = np.array([[1, 2, 3],
                         [4, 5, 6]])

b = np.array([10, 20, 30])


c =a+b
c

array([[11, 22, 33],
       [14, 25, 36]])

1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [333]:
# Answer Here
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.reduce(np.add, a, axis=1)
b

AttributeError: module 'numpy' has no attribute 'reduce'

In [340]:
c = np.array([1, 2, 3, 4, 5])
d = np.cumsum(c)

In [337]:
d

array([ 1,  3,  6, 10, 15])