In [5]:
import numpy as np

In [1]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

# Q.1
**Statement:** You are working with a retail store that needs to manage its inventory efficiently. They have provided you with a dataset containing information about products, their quantities in stock, and the number of units sold daily for the past week. Total number of products are 5. Your task is to calculate the following:



1.The total sales for each product over the past week.
\
2.The average daily sales for each product.

3.The product with the highest sales.

4.The product with the lowest sales.

5.The total sales for all products combined.

You are required to use NumPy for efficient data processing and calculations. Write code to solve this inventory management problem.

In [68]:
import numpy as np

# Sample data (replace with your actual data)
product_names = np.array(['Product A', 'Product B', 'Product C', 'Product D', 'Product E'])
quantities_in_stock = np.array([100, 150, 200, 250, 50])

daily_sales_data = np.array([[10, 15, 20, 25, 30, 35, 40],
                             [5, 7, 8, 10, 12, 14, 16],
                             [15, 20, 25, 30, 35, 40, 40],
                             [12, 25, 20, 40, 20, 32, 55],
                             [15, 20, 25, 30, 35, 40, 45]])

# Calculate total sales revenue for each product over the past week
a=np.sum(daily_sales_data,axis=(1))
print(a)
# Calculate average daily sales for each product
b=np.mean(daily_sales_data,axis=(1))
print(b,'\n')
# Find the product with the highest and lowest sales
c=np.argmax(a)
print('the product with the highest sales is product number: ',c,'\n')
d=np.argmin(a)
print('the product with the lowest sales is ',d,'\n')
# The total sales for all products combined.
total_sales_for_all_products_combined=np.sum(daily_sales_data)
total_sales_for_all_products_combined
#Revenue

# Calculate total sales revenue for all products combined
product_prices = np.array([5, 8, 10, 15, 20])

print('The daily sales of each product for the past week:', daily_sales_data, '\n')
revenue = daily_sales_data * product_prices[:, np.newaxis]
print(revenue,'\n')
print('the total revenue of all the products combined is',revenue.sum())

[175  72 205 204 210]
[25.         10.28571429 29.28571429 29.14285714 30.        ] 

the product with the highest sales is product number:  4 

the product with the lowest sales is  1 

The daily sales of each product for the past week: [[10 15 20 25 30 35 40]
 [ 5  7  8 10 12 14 16]
 [15 20 25 30 35 40 40]
 [12 25 20 40 20 32 55]
 [15 20 25 30 35 40 45]] 

[[ 50  75 100 125 150 175 200]
 [ 40  56  64  80  96 112 128]
 [150 200 250 300 350 400 400]
 [180 375 300 600 300 480 825]
 [300 400 500 600 700 800 900]] 

the total revenue of all the products combined is 10761


# Q.2
**Statement:** Statement: You are working with a manufacturing plant that produces various components. They have provided you with data on the production rates of five different machines over the past month. Your task is to analyze the performance of these machines by calculating the following metrics:

1.The total production output for each machine over the past month.

2.The average daily production rate for each machine.

3.The machine with the highest total production output.

4.The machine with the lowest total production output.

The overall production efficiency of the plant, which is defined as the ratio of the total production output to the total number of hours worked, and working hour for each day is 2 hours.

In [7]:
# Sample data (replace with your actual data)
Names_of_Machines=np.array(['Machine A', 'Machine B', 'Machine C', 'Machine D', 'Machine E'])
# Generate random production rates between 100 and 200 for 5 machines and 30 days
production_rates= np.random.randint(100,200,size=(5,30))
print('production_rates',production_rates,'\n')

# Calculate total production output for each machine over the past month
total_production_output= np.sum(production_rates,axis=(1))
print('total production output',Names_of_Machines,total_production_output,'\n')

# Calculate average daily production rate for each machine

average_daily_production_rate= np.mean(production_rates,axis=(1))
print('average_daily_production_rate',Names_of_Machines,average_daily_production_rate,'\n')
# Find the machine with the highest and lowest total production output
highest_production_output=Names_of_Machines[total_production_output.argmax()]

print('highest_production_output',highest_production_output,'\n')
lowest_production_output=Names_of_Machines[total_production_output.argmin()]
print('lowest_production_output',lowest_production_output,'\n')
# Calculate the overall production efficiency of the plant

efficency= total_production_output%60
total_effinecny_of_the_plant=np.mean(efficency)
print('total_effinecny_of_the_plant is',total_effinecny_of_the_plant)

production_rates [[126 153 137 132 190 190 102 153 146 106 149 124 113 152 160 149 129 111
  107 175 128 185 144 151 188 102 197 111 117 151]
 [175 168 125 167 189 116 196 188 117 123 175 150 174 123 158 113 167 165
  181 137 172 145 121 147 168 131 118 124 127 182]
 [126 132 184 181 176 151 101 120 162 125 149 152 167 182 113 193 115 195
  138 168 174 184 165 117 129 151 130 159 111 187]
 [184 163 174 124 162 199 175 179 109 153 178 173 133 158 102 174 177 137
  143 125 135 197 182 114 180 189 176 103 175 120]
 [166 110 161 117 127 122 112 106 136 123 108 117 111 110 123 195 137 125
  150 142 182 180 186 124 180 182 175 151 134 110]] 

total production output ['Machine A' 'Machine B' 'Machine C' 'Machine D' 'Machine E'] [4278 4542 4537 4693 4202] 

average_daily_production_rate ['Machine A' 'Machine B' 'Machine C' 'Machine D' 'Machine E'] [142.6        151.4        151.23333333 156.43333333 140.06666667] 

highest_production_output Machine D 

lowest_production_output Machine E 

tota

# Q3:

**Statment**
You are working on a project that involves simulating sensor data for a network of 10 sensors over a period of 15 days. Each sensor collects data once per hour. Your task is to generate a NumPy array named sensor_data to represent this simulated sensor data and perform following statistical analysis on it.

Populate the sensor_data array with random floating-point values between 0.0 and 100.0
The generated values should represent sensor readings collected once per hour.

After generating the sensor_data array, perform the following statistical **calculations:**

1.Calculate the mean (average) sensor reading for each sensor over the 15 days.

2.Calculate the standard deviation of sensor readings for each sensor.

3.Calculate the maximum sensor reading for each sensor.

4.Calculate the minimum sensor reading for each sensor.

5.Calculate the overall mean sensor reading for all sensors and all days.

6.Calculate the overall standard deviation of sensor readings for all sensors an

In [145]:
import numpy as np

# Data Generation Requirements
num_sensors = 10
num_days = 15
hours_per_day = 24
shape = (num_sensors, num_days * hours_per_day)
sensor_data=np.random.uniform(0.0,100.0,size=(10,15,24))
print("The sensors readings are= ",('\n'),sensor_data,('\n'))
 #1.Calculate the mean (average) sensor reading for each sensor over the 15 days.
mean_sensor_reading= np.mean(sensor_data,axis=(2))
print("The average sensor reading of each sensor over the 15 days is= ",('\n'),mean_sensor_reading,('\n'))


The sensors readings are=  
 [[[46.81247176  4.00560817 45.07701061 ... 60.57642729 27.1584748
   88.86776853]
  [ 5.98734403 14.64475876 76.59995442 ... 22.31997862 90.99329591
    3.85142668]
  [45.13101599 45.94392307 62.27963281 ... 69.75004042 70.84665984
   72.55125954]
  ...
  [ 0.70919093 34.70081658 11.41402738 ... 39.53628974 73.76269324
   77.37316862]
  [70.10289481 62.67076427 56.34046479 ... 23.3987792   5.2128855
    1.0589498 ]
  [87.82041153  9.95297243 54.00016247 ... 68.52310595 58.80810775
   19.61953092]]

 [[37.46423068 84.05849836  8.05932588 ... 21.59444801 85.5861487
   97.42522655]
  [83.46736374 94.37372468 89.73973251 ... 36.97746879 71.10094787
   62.11863336]
  [33.46971553 46.2057302  89.10840501 ... 11.73961964 99.75123599
   37.19988453]
  ...
  [71.38319213 37.47356584 38.38322055 ... 30.85708176 80.22195958
   72.64922142]
  [91.82268779 96.35951118 85.9478097  ... 44.21590654 93.54973472
   43.96852172]
  [20.94764602  9.89539584 91.0154314  ... 62.8

In [136]:
#2.Calculate the standard deviation of sensor readings for each sensor.
standard_deviation_of_sensor_readings= np.std(sensor_data,axis=(1,2))
print("the standard deviation of sensor readings for each sensor= ",('\n'),standard_deviation_of_sensor_readings,('\n'))

the standard deviation of sensor readings for each sensor=  
 [28.51595774 29.17584693 28.85847208 28.03102919 29.20545302 28.34479788
 29.03230099 29.74668223 28.9111129  28.05982298] 



In [141]:
#3.Calculate the maximum sensor reading for each sensor.
the_maximum_sensor_reading_for_each_sensor=sensor_data.max(axis=(1,2))
print("the maximum sensor reading for each sensor= ",('\n'),the_maximum_sensor_reading_for_each_sensor,('\n'))

the maximum sensor reading for each sensor=  
 [99.80464284 99.82287516 99.79673288 99.62003071 99.78968685 99.91550387
 99.91126321 99.90786188 99.92453744 99.56737883] 



In [143]:
#4.Calculate the minimum sensor reading for each sensor.
the_minimum_sensor_reading_for_each_sensor=sensor_data.min(axis=(1,2))
print("the minimum sensor reading for each sensor= ",('\n'),the_minimum_sensor_reading_for_each_sensor,('\n'))

the minimum sensor reading for each sensor=  
 [0.06044742 0.08266744 0.51472765 0.57388078 0.10750594 0.68717921
 0.0114458  0.4288052  0.07506232 0.09882896] 



In [149]:
#5.Calculate the overall mean sensor reading for all sensors and all days.
the_overall_mean_sensor_reading_for_all_sensors_and_all_days= np.mean(sensor_data)
print('the overall mean sensor reading for all sensors and all days=',the_overall_mean_sensor_reading_for_all_sensors_and_all_days)

the overall mean sensor reading for all sensors and all days= 49.92235912625025


In [150]:
#6.Calculate the overall standard deviation of sensor readings for all sensors and all days

the_overall_standard_deviation_sensor_reading_for_all_sensors_and_all_days= np.std(sensor_data)
print('the overall standard deviation of sensor readings for all sensors and all days=',the_overall_standard_deviation_sensor_reading_for_all_sensors_and_all_days)

the overall standard deviation of sensor readings for all sensors and all days= 28.699546293044683


# Q4:

**Statement**: You are tasked with analyzing the exam scores of 30 students in a class over a period of 10 exams. The exam scores are represented as a NumPy, where each row corresponds to a different student, and each column represents their score in a specific exam.

Populate the exam_scores array with random integer values between 50 and 100 to simulate students' exam performance.

After generating the exam_scores array, perform the following tasks:

1.Calculate the average score for each student over the 10 exams.

2.Calculate the standard deviation of scores for each student.

3.Identify students who have consistently performed well, defined as those whose average score is above 85.

4.Identify students who may need additional support, defined as those whose average score is below 50.

Write code to create and populate the exam_scores array and then perform the specified statistical analysis and performance evaluation tasks on the data.





In [3]:
import numpy as np

# Create the exam_scores array (30 students, 10 exams)
num_students = 30
num_exams = 10

# Populate the exam_scores array with random scores between 50 and 100
exam_scores=np.random.randint(50,100,size=(30,10))
print("the exam socres are",'\n',exam_scores,'\n')
# 1. Calculate the average score for each student over the 10 exams
average_score=np.mean(exam_scores,axis=(1))
print("the average scores are:",'\n',average_score,'\n')
# 2. Calculate the standard deviation of scores for each student
standard_deviation_of_scores=np.std(exam_scores,axis=(1))
print("the the standard deviation of scores are:",'\n',standard_deviation_of_scores,'\n')

# 3. Identify students who have consistently performed well (average score > 75)
well_performing_students = np.where(average_score > 75)[0]
print('well performing student are',well_performing_students)
# 4. Identify students who may need additional support (average score < 73)
bad_performing_students=np.where(average_score < 73)[0]
print('bad performing students are',bad_performing_students)

the exam socres are 
 [[51 92 73 98 75 81 86 71 68 76]
 [78 88 57 92 62 56 82 67 55 94]
 [63 90 67 98 89 74 95 54 72 92]
 [67 59 62 89 89 82 95 50 66 73]
 [61 51 98 61 52 77 68 91 89 51]
 [75 84 73 89 60 96 66 90 67 50]
 [78 50 78 89 65 97 85 98 73 68]
 [82 99 63 55 87 61 84 59 93 59]
 [97 99 54 59 59 77 64 52 70 98]
 [82 81 89 53 78 65 78 82 61 80]
 [83 88 62 63 70 96 79 92 69 51]
 [97 73 63 56 70 68 99 83 64 67]
 [52 88 72 83 60 65 79 75 62 69]
 [52 71 61 92 76 62 59 80 58 91]
 [67 75 98 88 58 69 85 80 76 61]
 [73 55 52 99 93 55 83 52 69 59]
 [71 92 51 62 72 75 76 60 64 94]
 [84 74 94 62 94 87 99 52 58 93]
 [94 59 68 65 77 88 68 60 58 89]
 [86 52 64 57 64 59 72 54 86 77]
 [59 50 86 70 72 78 90 86 94 89]
 [60 50 90 50 72 58 71 87 91 98]
 [86 86 82 82 86 52 50 84 68 90]
 [61 96 60 63 60 53 73 72 51 62]
 [78 55 71 80 73 90 97 54 51 73]
 [51 87 77 54 51 60 58 97 84 93]
 [56 60 91 67 80 87 81 80 95 71]
 [98 71 56 58 60 63 92 99 54 74]
 [66 90 67 91 75 75 76 68 90 78]
 [87 62 59 95 94 53 7