# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

In [5]:
import numpy as np

### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [17]:
# Answer here
a=np.array([np.arange(10, 80, 5), np.arange(5, 47, 3)])
a

array([[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
       [ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44]])

### Now use indexing to select the 5th 7th and 11th columns

In [21]:
# Answer here
b=a[:,[4,6,10]]
b

array([[30, 40, 60],
       [17, 23, 35]])

### Select the 2nd row and fourth-last to second-last columns


In [33]:
#Answer here
c=a[1,-4:-1]
c

array([35, 38, 41])

### Select 3rd to 3rd last columns skipping every second column

In [53]:
# Answer here
d=a[:,2:-2:2]
d

array([[20, 30, 40, 50, 60],
       [11, 17, 23, 29, 35]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [62]:
# Answer here
g=a[:,-4:0:-2]
g

array([[60, 50, 40, 30, 20],
       [35, 29, 23, 17, 11]])

### We will work with the following array:

In [63]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [73]:
# Answer here
b=a[2:5:2,1:5:3]
b

array([[11, 14],
       [21, 24]])

### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [92]:
# Answer here
sub_array = a[[0, 2, 4]][:, [2, 3]]

print("Extracted Sub-array:")
print(sub_array)


Extracted Sub-array:
[[ 2  3]
 [12 13]
 [22 23]]


In [97]:
f=a[[0,2,4]][:,[2,3]]
f


array([[ 2,  3],
       [12, 13],
       [22, 23]])

### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [101]:
# Answer here
h=a[[1,3,4]][:,[1,3]]
h

array([[ 6,  8],
       [16, 18],
       [21, 23]])

In [115]:
d= a[1:4:2, 1:5]
d

array([[ 6,  7,  8,  9],
       [16, 17, 18, 19]])

### Change the values 1, 10, 19 and 22 in the array to -2


In [132]:
a = np.arange(25).reshape(5, 5)
b = [(0, 1), (2, 0), (3, 4), (4, 2)]

# Replace values at identified indices
for i, j in b:
    a[i, j] = -2
a

array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

### Repeat above using boolean indexing

In [133]:
# Answer here
a = np.arange(25).reshape(5, 5)


mask = (a == 1) | (a == 10) | (a == 19) | (a == 22)

a[mask] = -2
a

array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [135]:
# Answer here

a = np.arange(25).reshape(5, 5)

# Boolean mask for row selection
b = np.array([True, False, True, False, True])

# Slicing in the column dimension
c = slice(0, 4, 3)

# Combine boolean indexing and column slicing to extract the sub-array
d = a[b, c]

d


array([[ 0,  3],
       [10, 13],
       [20, 23]])

### Calculating the sum, min and max of all diagonal values

In [141]:
# Answer here
a = np.arange(25).reshape(5, 5)

# Extract diagonal values
b = np.diagonal(a)

# Calculate sum, min, and max of diagonal values
c = np.sum(b)
d = np.min(b)
e = np.max(b)
print(b)
print(c)
print(d)
print(e)

[ 0  6 12 18 24]
60
0
24


### Calculate the sum of differences between the 2nd row and 2nd last column

In [143]:
# Answer here
a = np.arange(25).reshape(5, 5)

b = np.sum(a[1, :] - a[:, -2])
b

-30

### Create a new array that is the sum of even rows and odd rows

In [144]:
# Answer here
a = np.arange(25).reshape(5, 5)

# Calculate the sum of even rows
b = np.sum(a[::2], axis=0)

# Calculate the sum of odd rows
c = np.sum(a[1::2], axis=0)

# Create a new array that is the sum of even rows and odd rows
d = b + c
print

array([50, 55, 60, 65, 70])

## You are done. Good job!