# Problem 1: Reshaping for Image Processing
You are working on an image processing project, and you have a grayscale image represented as a 1D NumPy array **img_data** of size **(m * n)**, where m and n are the dimensions of the image. Write a function **reshape_image(img_data, new_shape)** that takes the original image data and a tuple representing the new shape **(p, q)** of the image. Ensure that the total number of pixels remains unchanged. If it's not possible to reshape without changing the total number of pixels, return **None**.

In [ ]:
# Write your function in this cell

In [2]:
import numpy as np
#ef
img_data = np.arange(9)  # Assuming a 3x3 image
print(img_data)
reshape_image=img_data.reshape(3,3)
   # new_shape = (3, 3)


result = reshape_image
print(result)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
#def reshape_value(a, b):
    #original_img = np.prod(a.shape)
    #new_img = np.prod(b)
    #if original_img != new_img:
     #   return None
    #reshaped_img = np.reshape(a,b)
    #return reshaped_img

In [3]:
def reshape_image(img_data, new_shape):
    if np.prod(new_shape)!= img_data.size:
        return None
    else:
        return img_data.reshape(new_shape)

# Example usage
img_data = np.arange(9)  # Assuming a 3x3 image
new_shape = (3, 3)

result = reshape_image(img_data, new_shape)
print(result)
print(img_data.size)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
9


# Problem 2: Matrix Transpose
You are dealing with a dataset stored as a NumPy array **data_matrix** with dimensions **(m, n)**. Implement a function **transpose_matrix(data_matrix)** that returns the transpose of the given matrix.

In [4]:
# Write your function in this cell
def  transpose_matrix(data_matrix):
    return np.transpose(data_matrix)

In [72]:
import numpy as np

data_matrix = np.array([[1, 2,4 ,5, 6,7 ,8], [4, 5, 6,7,8,9,10]])
transposed_matrix = transpose_matrix(data_matrix)

print(transposed_matrix)

[[ 1  4]
 [ 2  5]
 [ 4  6]
 [ 5  7]
 [ 6  8]
 [ 7  9]
 [ 8 10]]


# Problem 3: Flattening for Data Processing
You have a 2D array representing data from different sensors. Write a function **flatten_sensor_data(sensor_data)** that takes a 2D NumPy array representing the sensor readings and returns a flattened 1D array.

In [7]:
# Write your function in this cell 
def flatten_sensor_data(sensor_data):
    flattened_data = sensor_data.flatten()
    return flattened_data

In [14]:
import numpy as np

sensor_data = np.array([[10, 20, 30], [40, 50, 60]])
flattened_data = flatten_sensor_data(sensor_data)
print(sensor_data)
print(flattened_data)

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]
