In [2]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [22]:
# Answer Here
a=np.arange(0,24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
a.sum()

276

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [24]:
# Answer Here
a=np.random.randint(0,9,size=(2,3,4,5))
a

array([[[[1, 5, 6, 7, 1],
         [7, 0, 2, 0, 4],
         [4, 4, 7, 7, 7],
         [0, 6, 2, 4, 2]],

        [[0, 1, 6, 4, 3],
         [1, 1, 0, 1, 7],
         [7, 0, 6, 1, 3],
         [8, 3, 3, 7, 4]],

        [[6, 6, 3, 3, 2],
         [5, 6, 0, 0, 1],
         [0, 6, 1, 6, 0],
         [6, 5, 3, 2, 0]]],


       [[[7, 7, 0, 1, 6],
         [6, 6, 6, 1, 1],
         [6, 7, 7, 6, 8],
         [7, 4, 6, 4, 6]],

        [[8, 5, 7, 1, 4],
         [5, 2, 2, 6, 5],
         [3, 5, 2, 6, 6],
         [2, 2, 3, 7, 7]],

        [[1, 4, 7, 4, 7],
         [0, 3, 5, 1, 1],
         [2, 0, 5, 6, 1],
         [1, 4, 1, 3, 8]]]])

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [29]:
# Answer
a.mean(axis=2)

array([[[3.  , 3.75, 4.25, 4.5 , 3.5 ],
        [4.  , 1.25, 3.75, 3.25, 4.25],
        [4.25, 5.75, 1.75, 2.75, 0.75]],

       [[6.5 , 6.  , 4.75, 3.  , 5.25],
        [4.5 , 3.5 , 3.5 , 5.  , 5.5 ],
        [1.  , 2.75, 4.5 , 3.5 , 4.25]]])

# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [34]:
# Answer Here
a=np.random.randint(0,50,size=(7,24,60))
a.mean(axis=(1,2))

array([24.30416667, 25.00694444, 24.75208333, 24.56805556, 24.62291667,
       24.81388889, 24.46319444])

Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [6]:
# Answer Here
a=np.random.randint(0,50,size=(4, 7, 24, 60))
a.max(axis=(0,2,3))

array([49, 49, 49, 49, 49, 49, 49])

# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [8]:
# Answer Here
a=np.random.randint(0,50,size=(100, 50, 3))
a.mean(axis=(0,1))

array([24.8202, 24.7854, 24.3522])

# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [60]:
# Answer Here
a=np.random.randint(0,50,size=(5, 6, 7))
a.size

210

In [61]:
a.mean(axis=(1,2))

array([24.42857143, 22.64285714, 24.4047619 , 23.42857143, 23.4047619 ])

In [62]:
a.std(axis=(1,2))

array([15.6405195 , 15.10096406, 14.08994833, 14.33135566, 15.30181988])

In [65]:
a.min(axis=(1,2))

array([1, 0, 1, 1, 0])

In [66]:
a.max(axis=(1,2))

array([49, 49, 48, 49, 49])